# -*- coding: utf-8 -*-
"""1-6_python_syntax.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lst5dl9_lbBdqiVh-MuonDTmM_fMLRjQ
"""

""" Reads a number from the user and prints "zero", "negative" or "positive"
    depending on the number's value.
"""
#
"""Exercise:
he program above crashes if the user types in any inappropriate characters 
when asked for a number. For example, "X" and "$" are not a part of any 
valid number. Add an "if" statement to the program above that checks to see 
if the userInput contains a valid number before attempting to convert it 
to an int."""

userInput = input("Please type a number: ") # prompt and read

if userInput.isdecimal():
   userInput = int (userInput)  # convert from string to int
   if userInput > 0:
       print ("positive")
   elif userInput < 0:
      print ("negative")
   else:
      print ("zero")
else:
  print("invalid input, must be an integer")